# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pack_unit', models.CharField(choices=[('MB', 'Megabyte'), ('GB', 'Gigabyte')], max_length=2, verbose_name='Pacote de dados (unidade)')),
                ('data_pack_value', models.PositiveIntegerField(verbose_name='Pacote de dados (valor)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Plano de Dados Adicional',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Nome do Plano')),
                ('minutes_franchise', models.IntegerField(default=0, verbose_name='Franquia de Minutos')),
                ('data_pack_unit', models.CharField(choices=[('MB', 'Megabyte'), ('GB', 'Gigabyte')], max_length=2, verbose_name='Pacote de dados (unidade)')),
                ('data_pack_value', models.PositiveIntegerField(verbose_name='Pacote de dados (valor)')),
                ('sms_pack_size', models.PositiveIntegerField(verbose_name='Pacote de SMS')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Plano',
            },
        ),
        migrations.CreateModel(
            name='SMSPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_pack_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pacote de SMS')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Plano de SMS Adicional',
                'verbose_name_plural': 'Planos de SMS Adicionais',
            },
        ),
    ]
