# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='sms_pack_size',
            field=models.IntegerField(default=0, verbose_name='Pacote de SMS'),
        ),
    ]
